# Generated by Django 5.1.7 on 2025-04-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('happening_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('happening_description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('url', models.TextField()),
                ('happening_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
