# Generated by Django 5.2 on 2025-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('happening_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('category', models.CharField(choices=[('Omaha Area Event', 'Omaha Area Event'), ('Place to Visit', 'Place to Visit'), ('Family Activity', 'Family Activity'), ('Great Place to Eat', 'Great Place to Eat')], default='Omaha Area Event', max_length=100)),
                ('happening_description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='happenings/')),
                ('url', models.TextField(blank=True, null=True)),
                ('happening_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
