# Generated by Django 5.1.7 on 2025-04-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happening',
            name='category',
            field=models.CharField(choices=[('Omaha Area Event', 'Omaha Area Event'), ('Place to Visit', 'Place to Visit'), ('Family Activity', 'Family Activity'), ('Great Place to Eat', 'Great Place to Eat')], default='Omaha Area Event', max_length=100),
        ),
    ]
