# Generated by Django 5.1.7 on 2025-04-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0002_alter_happening_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happening',
            name='photo',
            field=models.ImageField(upload_to='happening_images'),
        ),
    ]
