# Generated by Django 5.1.7 on 2025-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0005_alter_happening_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happening',
            name='photo',
            field=models.ImageField(upload_to='happenings/static/happenings/'),
        ),
    ]
