# Generated by Django 5.2 on 2025-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0008_alter_happening_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
