# Generated by Django 5.2 on 2025-04-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0009_happening_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happening',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='happenings/'),
        ),
        migrations.AlterField(
            model_name='happening',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
