# Generated by Django 5.2 on 2025-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('pending', 'Pending'), ('available', 'Available')], max_length=10),
        ),
    ]
