# Generated by Django 5.2 on 2025-04-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_photo',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_name',
            field=models.CharField(choices=[('Aksarben Village', 'aksarben village'), ('Benson', 'benson'), ('Blackstone', 'blackstone'), ('Downtown', 'downtown'), ('Dundee', 'dundee'), ('Elkhorn', 'elkhorn'), ('Field Club', 'field club'), ('Midtown Crossing', 'midtown crossing'), ('Millard', 'millard'), ('Old Market', 'old market'), ('Regency', 'regency'), ('South Omaha', 'south omaha'), ('West Omaha', 'west omaha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='price_search',
            name='price_range',
            field=models.CharField(choices=[('400001 - 450000', '400001 - 450000'), ('900001 - 950000', '900001 - 950000'), ('300001 - 350000', '300001 - 350000'), ('850001 - 900000', '850001 - 900000'), ('500001 - 550000', '500001 - 550000'), ('250001 - 300000', '250001 - 300000'), ('450001 - 500000', '450001 - 500000'), ('800001 - 850000', '800001 - 850000'), ('150001 - 200000', '150001 - 200000'), ('750001 - 800000', '750001 - 800000'), ('550001 - 600000', '550001 - 600000'), ('950001 - 1000000', '950001 - 1000000'), ('350001 - 400000', '350001 - 400000'), ('650001 - 700000', '650001 - 700000'), ('700001 - 750000', '700001 - 750000'), ('100001 - 150000', '100001 - 150000'), ('50001 - 100000', '50001 - 100000'), ('600001 - 650000', '600001 - 650000'), ('200001 - 250000', '200001 - 250000')], max_length=100),
        ),
    ]
