# Generated by Django 5.2 on 2025-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_photo_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_name',
            field=models.CharField(choices=[('Aksarben Village', 'Aksarben Village'), ('Benson', 'Benson'), ('Blackstone', 'Blackstone'), ('Downtown', 'Downtown'), ('Dundee', 'Dundee'), ('Elkhorn', 'Elkhorn'), ('Field Club', 'Field Club'), ('Midtown Crossing', 'Midtown Crossing'), ('Millard', 'Millard'), ('Old Market', 'Old Market'), ('Regency', 'Regency'), ('South Omaha', 'South Omaha'), ('West Omaha', 'West Omaha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='price_search',
            name='price_range',
            field=models.CharField(choices=[('350001 - 400000', '350001 - 400000'), ('300001 - 350000', '300001 - 350000'), ('600001 - 650000', '600001 - 650000'), ('400001 - 450000', '400001 - 450000'), ('900001 - 950000', '900001 - 950000'), ('700001 - 750000', '700001 - 750000'), ('950001 - 1000000', '950001 - 1000000'), ('250001 - 300000', '250001 - 300000'), ('650001 - 700000', '650001 - 700000'), ('450001 - 500000', '450001 - 500000'), ('100001 - 150000', '100001 - 150000'), ('850001 - 900000', '850001 - 900000'), ('800001 - 850000', '800001 - 850000'), ('50001 - 100000', '50001 - 100000'), ('550001 - 600000', '550001 - 600000'), ('500001 - 550000', '500001 - 550000'), ('150001 - 200000', '150001 - 200000'), ('750001 - 800000', '750001 - 800000'), ('200001 - 250000', '200001 - 250000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property_type',
            name='property_type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Colonial', 'Colonial'), ('Condominium', 'Condominium'), ('Craftsman', 'Craftsman'), ('Log Cabin', 'Log Cabin'), ('Modern', 'Modern'), ('Ranch', 'Ranch'), ('Split Level', 'Split Level'), ('Townhome', 'Townhome'), ('Tudor', 'Tudor'), ('Victorian', 'Victorian')], max_length=100),
        ),
    ]
