# Generated by Django 5.2 on 2025-04-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available'), ('pending', 'Pending')], max_length=10),
        ),
    ]
