# Generated by Django 5.2 on 2025-04-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing_photo',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_url', models.ImageField(blank=True, upload_to='listing_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=10),
        ),
    ]
