# Generated by Django 5.2 on 2025-04-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_photo_alter_listing_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('sold', 'Sold')], max_length=10),
        ),
    ]
